// noinspection SpellCheckingInspection

export declare interface InterventoInterface {
  id: string,
  proComT: any,
  comune: string,
  unione: string,
  ambitoStrategico: string,
  ambitoStrategicoDettaglio: string,
  categoria: string,
  descrizione: string,
  fine: number,
  importoFonteDettaglio: string,
  importoFonti: string,
  importoPubblico: number,
  importoTotale: number,
  indirizzo: string,
  inizio: number,
  lat: number,
  link: string,
  long: number,
  nome: string,
  partecipazione: string,
  stato: string,
  target: string,
  tema: string,
  tipologia: string,
}
